<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('booking_types')->insert([
            // --- อัตราค่าเช่าสนามรายชั่วโมง ---
            // กลางแจ้ง (Outdoor)
            [
                'name'                          => 'รายชั่วโมง: กลางแจ้ง อังคาร-ศุกร์ 09.00-18.00 น.',
                'description'                   => 'ราคาเช่าสนามกลางแจ้ง อังคาร-ศุกร์ ช่วงเวลา 09.00-18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 350.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'weekday',
                'start_time_applicable'         => '09:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: กลางแจ้ง เสาร์-อาทิตย์ 09.00-18.00 น.',
                'description'                   => 'ราคาเช่าสนามกลางแจ้ง เสาร์-อาทิตย์ ช่วงเวลา 09.00-18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 400.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'weekend',
                'start_time_applicable'         => '09:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: กลางแจ้ง อังคาร-ศุกร์ 18.00-22.00 น.',
                'description'                   => 'ราคาเช่าสนามกลางแจ้ง อังคาร-ศุกร์ ช่วงเวลา 18.00-22.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 600.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'weekday',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '22:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: กลางแจ้ง เสาร์-อาทิตย์ 18.00-22.00 น.',
                'description'                   => 'ราคาเช่าสนามกลางแจ้ง เสาร์-อาทิตย์ ช่วงเวลา 18.00-22.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 700.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'weekend',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '22:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],

            // หลังคา (Covered)
            [
                'name'                          => 'รายชั่วโมง: หลังคา อังคาร-ศุกร์ 09.00-18.00 น.',
                'description'                   => 'ราคาเช่าสนามมีหลังคา อังคาร-ศุกร์ ช่วงเวลา 09.00-18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 450.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'weekday',
                'start_time_applicable'         => '09:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: หลังคา เสาร์-อาทิตย์ 09.00-18.00 น.',
                'description'                   => 'ราคาเช่าสนามมีหลังคา เสาร์-อาทิตย์ ช่วงเวลา 09.00-18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 500.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'weekend',
                'start_time_applicable'         => '09:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: หลังคา อังคาร-ศุกร์ 18.00-22.00 น.',
                'description'                   => 'ราคาเช่าสนามมีหลังคา อังคาร-ศุกร์ ช่วงเวลา 18.00-22.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 600.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'weekday',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '22:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'รายชั่วโมง: หลังคา เสาร์-อาทิตย์ 18.00-22.00 น.',
                'description'                   => 'ราคาเช่าสนามมีหลังคา เสาร์-อาทิตย์ ช่วงเวลา 18.00-22.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'hourly',
                'base_price'                    => 700.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'weekend',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '22:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => null,
                'created_at'                    => now(), 'updated_at' => now(),
            ],

            // --- อัตราค่าเช่าสนามประเภทเหมาวัน (Fixed Price 08.00 - 18.00 น.) ---
            // การกุศล
            [
                'name'                          => 'เหมาวัน: 2 สนาม (การกุศล) 08.00-18.00 น.',
                'description'                   => 'การจองเหมา 2 สนามเพื่อการกุศล ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 5000.00,
                'field_type_applicable'         => 'multi', // Indicates 2 fields
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 2,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'เหมาวัน: กลางแจ้ง (การกุศล) 08.00-18.00 น.',
                'description'                   => 'การจองสนามกลางแจ้งเหมาวันเพื่อการกุศล ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 2000.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'เหมาวัน: หลังคา (การกุศล) 08.00-18.00 น.',
                'description'                   => 'การจองสนามมีหลังคาเหมาวันเพื่อการกุศล ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 3500.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],

            // รายการแข่งขัน
            [
                'name'                          => 'เหมาวัน: 2 สนาม (แข่งขัน) 08.00-18.00 น.',
                'description'                   => 'การจองเหมา 2 สนามเพื่อการแข่งขัน ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 9000.00,
                'field_type_applicable'         => 'multi',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 2,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'เหมาวัน: กลางแจ้ง (แข่งขัน) 08.00-18.00 น.',
                'description'                   => 'การจองสนามกลางแจ้งเหมาวันเพื่อการแข่งขัน ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 4000.00,
                'field_type_applicable'         => 'outdoor',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'เหมาวัน: หลังคา (แข่งขัน) 08.00-18.00 น.',
                'description'                   => 'การจองสนามมีหลังคาเหมาวันเพื่อการแข่งขัน ช่วง 08.00 - 18.00 น.',
                'is_active'                     => true,
                'type_category'                 => 'full_day_fixed',
                'base_price'                    => 6000.00,
                'field_type_applicable'         => 'covered',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '08:00:00',
                'end_time_applicable'           => '18:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'มัดจำ 50% วันจอง, ชำระส่วนที่เหลือพร้อมเงินประกัน 2,000 บาท ล่วงหน้า 5 วันก่อนใช้สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],

            // --- นอกเวลา (หลัง 18.00 น.) สำหรับเหมาวัน (คิดเป็นรายชั่วโมง) ---
            [
                'name'                          => 'นอกเวลา: การกุศล (หลัง 18.00-21.00 น.)',
                'description'                   => 'อัตราค่าเช่ารายชั่วโมงสำหรับงานการกุศลหลัง 18.00 น. ไม่เกิน 21.00 น. (ต่อสนาม)',
                'is_active'                     => true,
                'type_category'                 => 'full_day_hourly', // เป็นส่วนหนึ่งของเหมาวัน แต่คิดเป็นรายชั่วโมง
                'base_price'                    => 400.00,            // ราคาต่อชั่วโมงสำหรับช่วงนี้
                'field_type_applicable'         => 'any',             // ใช้ได้ทั้งกลางแจ้ง/หลังคา
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '21:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'คิดเป็นรายชั่วโมง/สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'นอกเวลา: แข่งขัน (หลัง 18.00-22.00 น.)',
                'description'                   => 'อัตราค่าเช่ารายชั่วโมงสำหรับรายการแข่งขันหลัง 18.00 น. ไม่เกิน 22.00 น. (ต่อสนาม)',
                'is_active'                     => true,
                'type_category'                 => 'full_day_hourly', // เป็นส่วนหนึ่งของเหมาวัน แต่คิดเป็นรายชั่วโมง
                'base_price'                    => 500.00,            // ราคาต่อชั่วโมงสำหรับช่วงนี้
                'field_type_applicable'         => 'any',             // ใช้ได้ทั้งกลางแจ้ง/หลังคา
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => '18:00:00',
                'end_time_applicable'           => '22:00:00',
                'num_fields_applicable'         => 1,
                'is_membership'                 => false,
                'membership_duration_hours'     => null,
                'membership_offpeak_multiplier' => 1.0,
                'notes_conditions'              => 'คิดเป็นรายชั่วโมง/สนาม',
                'created_at'                    => now(), 'updated_at' => now(),
            ],

            // --- อัตราค่าเช่าสนามประเภทบัตรสมาชิก ---
            [
                'name'                          => 'บัตรสมาชิก 10 ชม.',
                'description'                   => 'บัตรสมาชิกสำหรับเช่าสนาม 10 ชั่วโมง',
                'is_active'                     => true,
                'type_category'                 => 'membership',
                'base_price'                    => 2500.00, // นี่คือราคาแพ็คเกจ ไม่ใช่ราคาต่อชั่วโมง
                'field_type_applicable'         => 'any',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => null,
                'end_time_applicable'           => null,
                'num_fields_applicable'         => 1,
                'is_membership'                 => true,
                'membership_duration_hours'     => 10,
                'membership_offpeak_multiplier' => 2.0, // 1 ชม. = 2 ชม. ในช่วงนอกเวลา
                'notes_conditions'              => 'ใช้ภายใน 30 วัน',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'บัตรสมาชิก 15 ชม.',
                'description'                   => 'บัตรสมาชิกสำหรับเช่าสนาม 15 ชั่วโมง',
                'is_active'                     => true,
                'type_category'                 => 'membership',
                'base_price'                    => 3500.00,
                'field_type_applicable'         => 'any',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => null,
                'end_time_applicable'           => null,
                'num_fields_applicable'         => 1,
                'is_membership'                 => true,
                'membership_duration_hours'     => 15,
                'membership_offpeak_multiplier' => 2.0,
                'notes_conditions'              => 'ใช้ภายใน 45 วัน',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'บัตรสมาชิก 20 ชม.',
                'description'                   => 'บัตรสมาชิกสำหรับเช่าสนาม 20 ชั่วโมง',
                'is_active'                     => true,
                'type_category'                 => 'membership',
                'base_price'                    => 4500.00,
                'field_type_applicable'         => 'any',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => null,
                'end_time_applicable'           => null,
                'num_fields_applicable'         => 1,
                'is_membership'                 => true,
                'membership_duration_hours'     => 20,
                'membership_offpeak_multiplier' => 2.0,
                'notes_conditions'              => 'ใช้ภายใน 60 วัน',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
            [
                'name'                          => 'HOT PROMOTION VIP 20 ชม.',
                'description'                   => 'โปรโมชั่นบัตรสมาชิก VIP 20 ชั่วโมง พร้อมน้ำดื่ม 2 แพ็ค',
                'is_active'                     => true,
                'type_category'                 => 'membership',
                'base_price'                    => 5000.00,
                'field_type_applicable'         => 'any',
                'day_type_applicable'           => 'any',
                'start_time_applicable'         => null,
                'end_time_applicable'           => null,
                'num_fields_applicable'         => 1,
                'is_membership'                 => true,
                'membership_duration_hours'     => 20,
                'membership_offpeak_multiplier' => 2.0,
                'notes_conditions'              => 'ฟรี น้ำดื่ม 2 แพ็ค, ใช้ภายใน 60 วัน, ไม่สามารถนำไปใช้แข่งขันได้, ต้องจองล่วงหน้า 3 วัน',
                'created_at'                    => now(), 'updated_at' => now(),
            ],
        ]);
    }
}
